service: manage-account-service

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  region: us-east-1
  deploymentMethod: direct
  tracing:
    # Can only be true if API Gateway is inside a stack.
    apiGateway: true
    # Optional, can be true (true equals 'Active'), 'Active' or 'PassThrough'
    lambda: true

custom:
  # Enable warmup on all functions (only for production and staging)
  warmup:
    - production
    - staging
  serverless-offline:
    useChildProcesses: true


functions:
  user-app:
    handler: dist/apps/user-app/main.handler
    package:
      individually: true
      exclude:
        - "./**"
      include:
        - ./dist/apps/user-app/**
        - node_modules/**
    events: # HTTP API endpoint (API Gateway v2)
      - httpApi:
          method: any
          path: /users-api/{proxy+}
